export const MenuItemsMain = [
    {
        title:'Profil',
        url:'/entreprise/profil',
        cName:'nav-links'
    },
    {
        title:'Offres',
        url:'/entreprise/offre',
        cName:'nav-links'
    },
    {
        title:'Filtre',
        url:'/offre/filtre',
        cName:'nav-links'
    },
    {
        title:'Swipe',
        url:'/offre/swipe',
        cName:'nav-links'
    },
    {
        title:'Chat',
        url:'/offre/chat',
        cName:'nav-links'
    },
    {
        title:'Paramètres',
        url:'/entreprise/parametre',
        cName:'nav-links'
    }
    
]